print("-" * 36)
print("Tugas 1 SISOP Kelas - A")
print("-" * 36)
print("Nama : Safira Najma Pramiswari")
print("NPM : 21083010074")
print("-" * 36)
print("notes:")
print("-" * 36)
print("Halo dunia!")
print("Ini adalah skrip Bash pertamaku di Linux")
